name: MongoDB Plugin
description: Plugin for MongoDB, allows execution of script against any MongoDB database.
version: 1.0
icon: https://cdn.rawgit.com/clarive/cla-mongodb-plugin/master/public/icon/mongodb.svg?sanitize=true
url: https://github.com/clarive/cla-mongodb-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-mongodb-plugin
